name: Automatic Merge

on:
  push:
    branches:
      - test

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Merge Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout main
          git merge --no-ff --no-edit ${{ github.ref }}
          git push
